import { Mail, MapPin, Phone } from "lucide-react"
import { InnerPage } from "@/components/inner-page"
import { Button } from "@/components/ui/button"

export const metadata = { title: "Contact | Altitude Explorer Expeditions", description: "Contact our Skardu office to plan your next mountain adventure." }

export default function ContactPage() {
  return <InnerPage eyebrow="Plan your journey" title="Tell us where you want to go." intro="Share your dates, experience, and the kind of journey you are imagining. Our Skardu team will help you shape the right route." image="/images/tour-snow-lake.png">
    <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Visit or call</p><h2 className="mt-3 text-3xl font-extrabold">A real team, in a real mountain town.</h2><div className="mt-8 flex flex-col gap-5 text-sm"><p className="flex gap-4"><MapPin className="size-5 shrink-0 text-primary" /><span>Ali Chowk, near Hawa Market<br />Baltistan Silicon Lab, 1st Floor, 3rd Office<br />Skardu, Gilgit-Baltistan, Pakistan</span></p><a className="flex gap-4 hover:text-primary" href="tel:+923327525752"><Phone className="size-5 shrink-0 text-primary" /><span>+92 332 752 5752<br />+92 342 693 0403</span></a><a className="flex gap-4 hover:text-primary" href="mailto:hello@altitudeexplorer.pk"><Mail className="size-5 shrink-0 text-primary" /><span>hello@altitudeexplorer.pk</span></a></div></div><form className="rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Your name<input required name="name" className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3" /></label><label className="text-sm font-medium">Email address<input required type="email" name="email" className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3" /></label></div><label className="mt-5 block text-sm font-medium">What are you planning?<textarea required name="message" rows={6} className="mt-2 w-full rounded-md border border-input bg-background px-3 py-3" placeholder="Tell us about your dates, group, experience, and preferred destination..." /></label><Button type="submit" size="lg" className="mt-6 w-full">Send enquiry</Button><p className="mt-3 text-center text-xs text-muted-foreground">We usually respond within one working day.</p></form></section>
  </InnerPage>
}
